### PR TITLE
add zuul configuration request template

### PR DESCRIPTION
**Pull request by fkr**
discussed in today's OPS call.

### CODE REVIEW

**Comment by master-caster** [comment]
LGTM but..... :grin: 
after some research of the possibilities i found out that we may create an ["issue form"](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)
in that way we could clearly define what we need to know to achieve our goal.

The template does not make any constraints who and which repository is about to be added.
Since adding the repository to the configuration is only half the work the issuer needs to be informed to install
the corresponding scs zuul application.

**Review by master-caster — COMMENTED** [review]
LGTM

**Comment by fkr** [comment]
> LGTM but..... 😁 after some research of the possibilities i found out that we may create an ["issue form"](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) in that way we could clearly define what we need to know to achieve our goal.
> 
> The template does not make any constraints who and which repository is about to be added. Since adding the repository to the configuration is only half the work the issuer needs to be informed to install the corresponding scs zuul application.

very good point - feel free to push changes towards this on top of this PR.
After all, this was just a quick shot.

**Comment by fkr** [comment]
ping @master-caster @jschoone

**Review by jschoone — APPROVED** [review]

**Pull request merged**
